name: LCE
version: '${version}'
main: games.negative.lce.CombatPlugin
loader: games.negative.lce.loader.CombatPluginLoader
api-version: '1.21'
authors: ["ericlmao"]
dependencies:
  server:
    PlaceholderAPI:
      load: AFTER
      required: false
    packetevents:
      load: BEFORE
      required: true
    WorldGuard:
      load: BEFORE
      required: false